






/*
This file is generated, do not edit by hand. 
Consult readme.md
*/








#pragma once
namespace Ghidra {
struct D2PoolBlockStrc;
struct D2PoolStrc;
struct D2PoolBlockEntryStrc;
struct D2PoolManagerStrc;
union uD2UnitMode;
struct D2SeedStrc;
struct D2BitBufferStrc;
struct D2WaypointStrc;
struct D2UnitDataPlayerArenaStrc;
struct D2PetDataStrc;
struct D2PetStrc;
struct D2PetListStrc;
struct D2UnitDataPlayerPetsStrc;
struct D2UnitDataPlayerInteractedNPCStrc;
struct D2PartyDataStrc;
struct D2TimerStrc;
struct D2TimerListStrc;
struct D2TimerQueueStrc;
struct D2DrlgEnvironmentStrc;
struct D2TileLibraryHashRefStrc;
struct D2TileLibraryHashNodeStrc;
struct D2TileLibraryHashStrc;
struct D2TileRecordStrc;
struct D2TileLibraryEntryStrc;
struct D2DrlgTileDataStrc;
struct D2DrlgRoomTilesStrc;
struct D2DrlgCoordsStrc;
struct D2DrlgOrthStrc;
struct D2DrlgGridStrc;
struct D2DrlgVertexStrc;
struct D2DrlgOutdoorRoomStrc;
struct D2DrlgPresetRoomStrc;
union D2DrlgRoomExDataUnion;
struct D2DrlgTileGridStrc;
struct D2DrlgRoomTilesListStrc;
struct D2LvlMazeTxt;
struct D2LvlPrestTxt;
struct D2DrlgFileStrc;
struct D2DrlgMapStrc;
struct D2DrlgLevelDataPresetArea;
struct D2DrlgLevelDataWildernessLevel;
union D2DrlgLevelDataUnion;
struct D2DrlgActWarpsInfoStrc;
struct D2DrlgActMiscSubA0Strc;
struct D2DrlgStrc;
struct D2DrlgLevelStrc;
struct D2PresetUnitStrc;
struct D2DrlgCoordStrc;
struct D2RoomCoordListStrc;
struct D2DrlgCoordListStrc;
struct D2RoomExStrc;
struct D2DrlgDeleteStrc;
struct D2RoomCollisionGridStrc;
struct D2DrlgRoomCoordsStrc;
struct D2RoomStrc;
struct D2DrlgActStrc;
struct D2InactiveUnitListStrc;
struct D2MonsterRegionFieldStrc;
struct D2MonsterRegionStrc;
struct D2QuestGUIDStrc;
struct D2QuestArgStrcUnion1;
struct D2QuestArgStrcUnion2;
struct D2QuestArgStrcUnion3;
union uD2QuestArgStrcUnion;
struct D2QuestArgStrc;
struct D2QuestDataCallbacksStrc;
struct D2NPCMessageStrc;
struct D2NPCMessageTableStrc;
struct D2QuestDataStrc;
struct D2QuestTimerStrc;
struct D2QuestControlStrc;
struct D2UnitNodeStrc;
struct D2InventoryGridStrc;
struct D2InventoryGridInfoStrc;
struct D2InventoryStrc;
struct D2GameNpcStrc;
struct D2GameNpcArrayStrc;
struct D2GameNpcControlStrc;
struct D2ArenaControlStrc;
struct D2GameStrc;
struct D2PacketListStrc;
struct D2ClientHotKeyStrc;
struct D2PlayerBasicsData;
struct D2ClientStrc;
struct D2UnitDataPlayerStrc;
struct D2MonStatsTxtTC;
struct D2MonStatsTxt;
struct D2MonsterDataComponents;
struct D2MonStats2Txt;
struct D2AiParamStrc;
struct D2MonsterAiCmdStrc;
struct D2MonsterDataMinionList;
struct D2AiGeneralStrc;
struct D2MonsterNameStrc;
struct D2MonsterAiStrc;
struct D2UnitDataMonsterStrc;
struct D2ObjectsTxt;
struct D2ShrinesTxt;
struct D2UnitDataObjectStrc;
struct D2CoordsShort;
struct D2UnitDataMissileStrc;
struct D2UnitDataItemStrc;
union D2UnitDataUnion;
struct D2StaticPathStrc;
struct D2DynamicPathCoordsStrc;
union D2DynamicPathCoordsUnion;
struct D2PathPointStrc;
struct D2DynamicPathStrc;
union D2PathUnion;
struct D2AnimSeqStrc;
struct D2AnimDataRecordStrc;
struct D2AnimDataStrc;
struct D2GfxInfoUnkStrc;
struct D2ParticleOffset3DVectorStrc;
struct D2ParticleStrc;
struct D2GfxInfoStrc;
struct D2StatInfoStrc;
struct D2StatListStrc;
struct D2StateFlags;
struct D2StatListExStrc;
struct D2LightMapStrc;
struct D2TimerArgStrc;
struct D2CUnitEventStrc;
struct D2SUnitEventStrc;
union D2UnitEvent;
struct D2HoverTextStrc;
struct D2SkillsTxt;
struct D2SkillStrc;
struct D2SkillListStrc;
struct D2ServerCmdStrc;
struct D2SUnitMsgStrc;
struct D2UnitStrc;
class D2UnitPlayer; //: public D2UnitStrc;
class D2UnitMonster; //: public D2UnitStrc;
class D2UnitObject; //: public D2UnitStrc;
class D2UnitMissile; //: public D2UnitStrc;
class D2UnitItem; //: public D2UnitStrc;
class D2UnitWarp; //: public D2UnitStrc;
struct D2CharSelCompStrc;
struct D2CharSelStrc;
struct D2QServerClientPacketStrc;
struct D2QServerClientStrc;
struct D2QServerClientListStrc;
struct D2QServerStrc;
struct D2CharSelSaveDataStrc;
struct D2UnknownSequence;
struct D2IniConfigStrc;
struct DC6Block;
struct DC6;
struct D2ControlMsg;
struct D2ControlStrc;
struct FORMS_PredefinedFormStrc;
struct D2BoundingBoxStrc;
struct D2ItemUnknownServerSideStrc;
struct D2UnderMouseStrc;
struct D2PlayerClassTxt;
struct D2TxtLinkNodeStrc;
struct D2TxtLinkStrc;
struct D2BodyLocsTxt;
struct D2StorePageTxt;
struct D2ElemTypesTxt;
struct D2HitClassTxt;
struct D2MonModeTxtSmall;
struct D2PlrModeTxt;
struct D2SkillCalcTxt;
struct D2MissCalcTxt;
struct D2SkillsHeaderTxt;
struct D2EventsTxt;
struct D2CompCodeTxt;
struct D2MonAiTxt;
struct D2PropertiesTxt;
struct D2HireDescTxt;
struct D2StatesTxt;
struct D2StatesDataTbls;
struct D2AllStatesDataTbl;
struct D2SoundsTxtSmall;
struct D2HirelingTxt;
struct D2NpcTxt;
struct D2ColorsTxt;
struct D2ParsedTreasureClassSub0x28Strc;
struct D2ParsedTreasureClassStrc;
struct D2ParsedChestTreasureClassStrc;
struct D2ParsedActTreasureClassStrc;
struct D2ParsedDifficultyTreasureClassStrc;
struct D2MonSoundsTxt;
struct D2MonPlaceTxt;
struct D2MonPresetTxtPlace;
struct D2MonPresetTxt;
struct D2SuperUniquesTxt;
struct D2MissilesTxt;
struct D2MonLvlTxt;
struct D2MonSeqTxt;
struct D2MonSeqMonsterTbls;
struct D2SkillDescTxt;
struct D2SkillsPerClassCounter;
struct D2SkillsPerClassStrc;
struct D2PassiveSkillsPerClassStrc;
struct D2OverlayTxt;
struct D2CharItemStrc;
struct D2CharStatsTxt;
struct D2ItemStatCostTxt;
struct D2MonEquipTxt;
struct D2PetTypeTxt;
struct D2ItemTypesTxt;
struct D2SetsTxtPStrc;
struct D2SetsTxtFStrc;
struct D2UniqueSetItemsTxtEntry;
struct D2SetItemsTxtEntry;
struct D2SetItemsTxt;
struct D2SetsTxt;
struct D2UniqueItemsTxt;
struct D2MonPropTxtEntry;
struct D2MonPropTxt;
struct D2MonTypeTxt;
struct D2MonUModTxt;
struct D2LevelsTxt;
struct D2LevelDefsColor;
struct D2LevelDefsTxt;
struct D2ExperienceTxt;
struct D2DifficultyLevelsTxt;
struct D2DataTableTxtStrc;
struct D2CoordStrc;
}; // ghidra namespace